import { ValueAttribute } from './value';
import { ClickAttribute, OnEnterAttribute, OnEscapeAttribute } from './event';
import { StyleAttribute } from './style';
import { FocusAttribute } from './focus';
export * from './base';
export declare var value: typeof ValueAttribute;
export declare var onclick: typeof ClickAttribute;
export declare var onenter: typeof OnEnterAttribute;
export declare var onescape: typeof OnEscapeAttribute;
export declare var checked: typeof ValueAttribute;
export declare var style: typeof StyleAttribute;
export declare var focus: typeof FocusAttribute;
